'use client'
import {useEffect,useMemo,useState} from 'react'
import {supabase} from '@/lib/supabase'
type Song={id:string,title:string,artist:string,genre:string}
type Perf={song_id:string,performed_at:string}
export default function Home(){
 const [songs,setSongs]=useState<Song[]>([]),[perfs,setPerfs]=useState<Perf[]>([]),[q,setQ]=useState(''),[genre,setGenre]=useState('전체보기'),[sort,setSort]=useState('title'),[loading,setLoading]=useState(true)
 useEffect(()=>{(async()=>{const [s,p]=await Promise.all([supabase.from('songs').select('id,title,artist,genre'),supabase.from('performance_entries').select('song_id,performed_at')]);if(s.error||p.error){console.error(s.error||p.error)}else{setSongs(s.data||[]);setPerfs(p.data||[])}setLoading(false)})()},[])
 const stats=useMemo(()=>{const m=new Map<string,{count:number,last:string}>();for(const p of perfs){const x=m.get(p.song_id);if(!x)m.set(p.song_id,{count:1,last:p.performed_at});else{ x.count++; if(p.performed_at>x.last)x.last=p.performed_at}}return m},[perfs])
 const genres=useMemo(()=>['전체보기',...Array.from(new Set(songs.map(s=>s.genre))).sort((a,b)=>a.localeCompare(b,'ko'))],[songs])
 const rows=useMemo(()=>songs.filter(s=>(genre==='전체보기'||s.genre===genre)&&(!q||`${s.title} ${s.artist}`.toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>sort==='artist'?a.artist.localeCompare(b.artist,'ko'):sort==='count'?(stats.get(b.id)?.count||0)-(stats.get(a.id)?.count||0):a.title.localeCompare(b.title,'ko')),[songs,q,genre,sort,stats])
 const copy=(s:Song)=>navigator.clipboard.writeText(`${s.title} - ${s.artist}`)
 return <main><header><button className="menu">☰</button><div><small>SONG POP</small><h1>SUDAL</h1><p>수달 노래책</p></div></header><section className="controls"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="곡명 또는 가수 검색"/><div className="filters"><select value={genre} onChange={e=>setGenre(e.target.value)}>{genres.map(g=><option key={g}>{g}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="title">제목순</option><option value="artist">가수순</option><option value="count">많이 부른 순</option></select></div><b>검색 결과 {rows.length}곡</b></section>{loading?<div className="state">노래책을 불러오는 중...</div>:<section className="table"><div className="tr th"><span>순번</span><span>곡명</span><span>가수</span><span>장르</span><span>총 횟수</span><span>마지막으로 부른 날짜</span><span>지난 날짜</span><span>복사</span></div>{rows.map((s,i)=>{const st=stats.get(s.id);const days=st?Math.floor((Date.now()-new Date(st.last).getTime())/86400000):null;return <div className="tr" key={s.id}><span>{i+1}</span><strong>{s.title}</strong><span>{s.artist}</span><span className="tag">{s.genre}</span><span>{st?.count||0}</span><span>{st?new Date(st.last).toLocaleDateString('ko-KR'):'기록 없음'}</span><span>{days===null?'아직 부르지 않음':days===0?'오늘':`${days}일 전`}</span><button onClick={()=>copy(s)}>복사</button></div>})}</section>}</main>}
